### ISSUE TITLE
Design of source code lines for bytecode

### ISSUE THREAD

**Issue by codingpotato** [SeedV/SeedLang#153]
We have added `VISNOTIFY` opcode for visualizers notification. The code range or semantic info can be included in the corresponding event classes. It seems the code range is not needed for each instructor in the chunk class. Only a line number for each instructor is enough for indicate the line of source code that this instructor belongs to.
It helps to implement the pause and resume feature. And it can also reduce the memory needed.

```python
private readonly List<Instruction> _bytecode = new List<Instruction>();
# Remove ranges from the chunk class
# private readonly List<Range> _ranges = new List<Range>();
# Add line number for each instructor 
private readonly List<int> _lines = new List<int>();
```

But there are two problems for this design. First is sometime it's hard to match instructor to source code lines, for example:

```python
for i in (1, 2, 3):
  print(i)
```

The compiled bytecode are as following. Which source code line should the `FORLOOP` instructor belongs to? 1 or 2? I think maybe line 1 shall be highlight when the execution stops in instructor 16. How about instructor 17?

```text
(Line 1)  1    LOADK     1 -1             ; 1                 [Ln 1, Col 10 - Ln 1, Col 10]
(Line 1)  2    LOADK     2 -2             ; 2                 [Ln 1, Col 13 - Ln 1, Col 13]
(Line 1)  3    LOADK     3 -3             ; 3                 [Ln 1, Col 16 - Ln 1, Col 16]
(Line 1)  4    NEWTUPLE  0 1 3                                [Ln 1, Col 9 - Ln 1, Col 17]
(Line 1)  5    LOADK     1 -4             ; 0                 [Ln 1, Col 0 - Ln 2, Col 9]
(Line 1)  6    LEN       2 0 0                                [Ln 1, Col 0 - Ln 2, Col 9]
(Line 1)  7    LOADK     3 -1             ; 1                 [Ln 1, Col 0 - Ln 2, Col 9]
(Line 1)  8    FORPREP   1 7              ; to 16             [Ln 1, Col 0 - Ln 2, Col 9]
(Line 1)  9    GETELEM   4 0 1                                [Ln 1, Col 0 - Ln 2, Col 9]
(Line 1)  10   SETGLOB   4 6                                  [Ln 1, Col 0 - Ln 2, Col 9]
(Line 2)  11   GETGLOB   4 0                                  [Ln 2, Col 2 - Ln 2, Col 9]
(Line 2)  12   GETGLOB   5 4                                  [Ln 2, Col 2 - Ln 2, Col 6]
(Line 2)  13   GETGLOB   6 6                                  [Ln 2, Col 8 - Ln 2, Col 8]
(Line 2)  14   CALL      5 1 0                                [Ln 2, Col 2 - Ln 2, Col 9]
(Line 2)  15   CALL      4 1 0                                [Ln 2, Col 2 - Ln 2, Col 9]
(Line 1 or 2?)  16   FORLOOP   1 -8             ; to 9              [Ln 1, Col 0 - Ln 2, Col 9]
(Line 3?)  17   RETURN    0 0 
```

Second problem is there isn't line number for block programs. Should we use following classes to express source code line for block and text programs?

```sharp
class abstract SourceCodeLine {
}

class BlockLine: SourceCodeLine {
  public string BlockId;
}

class TextLine: SourceCodeLine {
  public int Line;
}
```

**Comment by wixette** [comment]
1. As for the first question, how to map source code lines to bytecode lines or vice versa, can we just follow the typical solution that common compilers/debuggers use to perform debug operations such as step in, step out, step over? E.g., how does gcc/gdb maps a c++ code `for (int i; i < 10; i++)` to compiled binary instructions?

2. For the class hierarchy, can we refactor the existing classes `TextPosition/BlocPosition` and `Range/TextRange/BlockRange` to support expressing a single line number as a range or position? In this way we do not need to introduce another group of classes such as `SourceCodeLine/BlockLine/TextLine`?

**Comment by codingpotato** [comment]
As we discussed, I will just ignore the dependency of Block component, and use line number (int type) to indicate the source code line of each bytecode in current phase.

**Comment by codingpotato** [comment]
Closed this issue, because the TextRange is enough for now. Don't need optimization now.
